package com.databps.bigdaf.chiwen.audit;

import com.databps.bigdaf.chiwen.util.ChiWenAccessResultProcessor;
import java.util.Collection;
import java.util.List;

/**
 * @author merlin
 * @create 2017-11-04 下午4:23
 */
public interface HbaseAuditHandler extends ChiWenAccessResultProcessor {

  List<AuthzAuditEvent> getCapturedEvents();

  void logAuthzAudits(Collection<AuthzAuditEvent> auditEvents);

  /**
   * Discards and returns the last audit events captured by the audit handler.  Last audit event should be the ones generated during the most recent authorization request.
   * However, it won't be all of the audit events called during an authorize call since implementation class may not override the method which takes a list of responses -- in
   * which case there would be several audit messages generated by one call but this only allows you to get last of those messages created during single auth request.
   * After this call the last set of audit events won't be returned by <code>getCapturedEvents</code>.
   * @return
   */
  AuthzAuditEvent getAndDiscardMostRecentEvent();

  /**
   * This is a complement to <code>getAndDiscardMostRecentEvent</code> to set the most recent events.  Often useful to un-pop audit messages that were take out.
   * @param capturedEvents
   */
  void setMostRecentEvent(AuthzAuditEvent capturedEvents);

  /**
   * Is audit handler being used in context of a access authorization of a superuser?
   * @param override
   */
  void setSuperUserOverride(boolean override);
}

