[#ftl strip_whitespace=true]

[#include "ftl/ui/page.ftl"/]
[#include "ftl/ui/mongo_page.ftl"/]
[#include "ftl/ui/select.ftl"/]
[#include "ftl/ui/radio.ftl"/]
[#include "ftl/ui/checkboxlist.ftl"/]
[#include "ftl/ui/value.ftl"/]
[#include "ftl/ui/date.ftl"/]
[#include "ftl/ui/tooltip.ftl"/]