<#--
<input type="radio"/>
-->
[#macro radio
	list listKey="" listValue="" value="" name=""
	 required="false" rule="" onclick="" params=""
	]
[#if list?is_sequence]
	[#if listKey!="" && listValue!=""]
		[#list list as item]
			[#local rkey=item[listKey]]
			[#local rvalue=item[listValue]]
			[#local index=item_index]
			[#local hasNext=item_has_next]
			[#include "/ftl/ui/radio-item.ftl"][#t/]
		[/#list]
	[#else]
		[#list list as item]
			[#local rkey=item]
			[#local rvalue=item]
			[#local index=item_index]
			[#local hasNext=item_has_next]
			[#include "/ftl/ui/radio-item.ftl"][#t/]
		[/#list]
	[/#if]
[#else]
	[#list list?keys as key]
		[#local rkey=key/]
		[#local rvalue=list[key]/]
		[#local index=key_index]
		[#local hasNext=key_has_next]
		[#include "/ftl/ui/radio-item.ftl"][#t/]
	[/#list]
[/#if]
[/#macro]